"""Initial migration with image field

Revision ID: 2cf06cdd1b9e
Revises: 2356e1ec23bd
Create Date: 2023-10-05 09:38:49.424429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf06cdd1b9e'
down_revision = '2356e1ec23bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meals', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
